"""Public facade for RepoDossier's structured export model.

This module gives future exporter and renderer migration code one stable
import surface while the internal helper modules remain small and focused.
"""

from __future__ import annotations

from repodossier.export_model import (
    CallGraphReport,
    DatabaseSchemaReport,
    DependencyReport,
    ExportConfigurationSummary,
    ExportMode,
    ExportModelValidationError,
    ExportSummary,
    ExportWarning,
    FileEntry,
    FileStatus,
    FileTreeEntry,
    ImportGraphReport,
    LanguageStatistics,
    RecentCommitReport,
    RepositoryExport,
    RepositoryMetadata,
    SecretDetectionSummary,
    SymbolIndex,
    TestMapReport,
    TextStatus,
    assert_valid_repository_export,
    empty_repository_export,
    validate_repository_export,
)
from repodossier.export_model_configuration import (
    make_export_configuration_summary,
    merge_configuration_summaries,
    normalize_configuration_mapping,
    normalize_configuration_paths,
    normalize_configuration_patterns,
)
from repodossier.export_model_content import (
    content_line_count,
    content_size_bytes,
    estimate_tokens_from_content,
    file_entry_content_for_rendering,
    file_entry_has_exportable_content,
    make_file_entry_from_content,
)
from repodossier.export_model_factory import (
    make_minimal_repository_export,
    make_repository_export,
)
from repodossier.export_model_finalize import (
    finalize_repository_export,
    refresh_repository_export_derived_sections,
    replace_repository_export_files,
    repository_export_with_files,
)
from repodossier.export_model_index import (
    file_index_by_path,
    files_by_language,
    files_by_status,
    filter_files_by_language,
    filter_files_by_status,
    get_file_entry,
    iter_known_files,
    language_counts_from_export,
    status_counts_from_export,
)
from repodossier.export_model_modes import (
    MODE_DEFAULT_SECTIONS,
    MODE_TITLES,
    VALID_EXPORT_MODES,
    export_mode_default_sections,
    export_mode_includes_source_content,
    export_mode_is_review_focused,
    export_mode_title,
    is_valid_export_mode,
    normalize_export_mode,
    repository_export_default_sections,
    repository_export_title,
)
from repodossier.export_model_paths import (
    ancestor_export_paths,
    export_path_depth,
    export_path_name,
    export_path_parent,
    export_path_sort_key,
    normalize_export_path,
    normalize_export_paths,
    sort_export_paths,
)
from repodossier.export_model_repository import (
    make_repository_metadata,
    normalize_optional_text,
    normalize_repository_root_name,
    normalize_repository_root_path,
    repository_metadata_display_name,
    repository_metadata_has_git,
    repository_name_from_root_path,
    update_repository_git_metadata,
)
from repodossier.export_model_reports import (
    make_call_graph_report,
    make_database_schema_report,
    make_dependency_report,
    make_import_graph_report,
    make_recent_commit_report,
    make_secret_detection_summary,
    make_symbol_index,
    make_test_map_report,
    normalize_report_items,
    normalize_report_mapping,
)
from repodossier.export_model_serialization import (
    repository_export_to_dict,
    to_plain_data,
)
from repodossier.export_model_summary import (
    build_export_summary,
    build_export_summary_from_export,
    count_files_by_language,
    count_files_by_status,
    file_type_statistics_from_files,
    language_statistics_from_files,
)
from repodossier.export_model_tree import (
    build_file_tree,
    build_file_tree_from_entries,
    build_file_tree_from_export,
    flatten_file_tree,
    tree_paths,
)
from repodossier.export_model_warnings import (
    append_export_warnings,
    make_export_warning,
    normalize_export_warnings,
    warning_counts_by_code,
    warning_messages,
    warnings_by_path,
)


__all__ = (
    "CallGraphReport",
    "DatabaseSchemaReport",
    "DependencyReport",
    "ExportConfigurationSummary",
    "ExportMode",
    "ExportModelValidationError",
    "ExportSummary",
    "ExportWarning",
    "FileEntry",
    "FileStatus",
    "FileTreeEntry",
    "ImportGraphReport",
    "LanguageStatistics",
    "MODE_DEFAULT_SECTIONS",
    "MODE_TITLES",
    "RecentCommitReport",
    "RepositoryExport",
    "RepositoryMetadata",
    "SecretDetectionSummary",
    "SymbolIndex",
    "TestMapReport",
    "TextStatus",
    "VALID_EXPORT_MODES",
    "ancestor_export_paths",
    "append_export_warnings",
    "assert_valid_repository_export",
    "build_export_summary",
    "build_export_summary_from_export",
    "build_file_tree",
    "build_file_tree_from_entries",
    "build_file_tree_from_export",
    "content_line_count",
    "content_size_bytes",
    "count_files_by_language",
    "count_files_by_status",
    "empty_repository_export",
    "estimate_tokens_from_content",
    "export_mode_default_sections",
    "export_mode_includes_source_content",
    "export_mode_is_review_focused",
    "export_mode_title",
    "export_path_depth",
    "export_path_name",
    "export_path_parent",
    "export_path_sort_key",
    "file_entry_content_for_rendering",
    "file_entry_has_exportable_content",
    "file_index_by_path",
    "file_type_statistics_from_files",
    "files_by_language",
    "files_by_status",
    "filter_files_by_language",
    "filter_files_by_status",
    "finalize_repository_export",
    "flatten_file_tree",
    "get_file_entry",
    "is_valid_export_mode",
    "iter_known_files",
    "language_counts_from_export",
    "language_statistics_from_files",
    "make_call_graph_report",
    "make_database_schema_report",
    "make_dependency_report",
    "make_export_configuration_summary",
    "make_export_warning",
    "make_file_entry_from_content",
    "make_import_graph_report",
    "make_minimal_repository_export",
    "make_recent_commit_report",
    "make_repository_export",
    "make_repository_metadata",
    "make_secret_detection_summary",
    "make_symbol_index",
    "make_test_map_report",
    "merge_configuration_summaries",
    "normalize_configuration_mapping",
    "normalize_configuration_paths",
    "normalize_configuration_patterns",
    "normalize_export_mode",
    "normalize_export_path",
    "normalize_export_paths",
    "normalize_export_warnings",
    "normalize_optional_text",
    "normalize_repository_root_name",
    "normalize_repository_root_path",
    "normalize_report_items",
    "normalize_report_mapping",
    "refresh_repository_export_derived_sections",
    "replace_repository_export_files",
    "repository_export_default_sections",
    "repository_export_title",
    "repository_export_to_dict",
    "repository_export_with_files",
    "repository_metadata_display_name",
    "repository_metadata_has_git",
    "repository_name_from_root_path",
    "sort_export_paths",
    "status_counts_from_export",
    "to_plain_data",
    "tree_paths",
    "update_repository_git_metadata",
    "validate_repository_export",
    "warning_counts_by_code",
    "warning_messages",
    "warnings_by_path",
)

__all__ = tuple(sorted(__all__))
